#!/bin/bash
# In order use this script and pull ip address from the network it will use the tool nmap and scan the network
# subnet and save it to a text file call Network.txt
#
#
# This will install the the command line program called
# nmap for debian distro
apt-get install nmap
#
#
#
echo "Enter the network id"
read NetworkID
nmap -sn $NetworkID > /home/users/lwm/Desktop/network/Network.txt



